### ISSUE TITLE
I can't use the library

### ISSUE THREAD

**Issue by ignacio-pascual-plunge** [paugit/tinyaudiodecoder#1]
Every time I use TinyAudioDecoder::Initialize(...) is returning me TINYAD_RESULT_INVALID_FILE code. What should I put in first param, buffer of audio file or filename? If buffer, what format, encode audio bytes, whole file?

I'm compiling for iOS.

**Comment by paugit** [comment]
Really sorry I did not notice this issue months ago. Haven't had time to touch this project for 2 years. Probably does not help you anymore but the string is a file name like "mysound.wav" that exists in the main bundle. The file must be in your XCode project and also in your Project/Build Phases/Copy Bundle Resources list. You must also pass the bundle to the TinyAudioDecoder::Initialize(...)

``` c
TinyAudioDecoderIosExtras platformExtras;
platformExtras.bundle = CFBundleGetMainBundle();

...

TinyAudioDecoder *decoder = new TinyAudioDecoder();

if(decoder->Initialize(file, 44100, true, &dstBuffer, &platformExtras)
```

The bundle could be some other bundle too.
