### ISSUE TITLE
test app?

### ISSUE THREAD

**Issue by jbloit** [paugit/tinyaudiodecoder#2]
Hi, 
If anyone has a working test app example using this library, it would be greatly appreciated. I've been trying to use it, but it crashes on Initialization of the decoder. Maybe I'm doing something wrong...

My test app is on the TinyAudioDecoder branch of this repo: 

https://github.com/jbloit/android_decodeMP3_testApp/tree/tinyAudioDecoder

Thanks!

**Comment by paugit** [comment]
Really sorry for late answer. Unfortunately can't remember much about this project since it is really old. It could be that your platform extras is initialized with garbage since you are not using {}. You could try setting

platformExtras.engineObject = NULL;
platformExtras.engine = NULL;
